services:
  orthanc-db:
    image: postgres:15-alpine
    container_name: orthanc-db
    restart: always
    environment:
      POSTGRES_USER: orthanc
      POSTGRES_PASSWORD: orthancpassword
      POSTGRES_DB: orthanc
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - pacs

  app-db:
    image: postgres:15-alpine
    container_name: app-db
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: pacsuser
      POSTGRES_PASSWORD: pacspassword
      POSTGRES_DB: pacsweb
    volumes:
      - ./app_postgres_data:/var/lib/postgresql/data
    networks:
      - pacs

  pacs:
    container_name: orthanc
    image: jodogne/orthanc-plugins
    ports:
      - 8042:8042
      - 4242:4242
    volumes:
      - ./orthanc.json:/etc/orthanc/orthanc.json:ro
      - ./orthanc_db:/var/lib/orthanc/db/
    restart: always
    depends_on:
      - orthanc-db
    networks:
      - pacs

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pacs-web
    ports:
      - 3001:3001
    environment:
      - DATABASE_URL=postgresql://pacsuser:pacspassword@app-db:5432/pacsweb
      - AUTH_SECRET=yoursecretphrasehere
      - AUTH_TRUST_HOST=true
      - ORTHANC_URL=http://pacs:8042
      - ORTHANC_USERNAME=quantum
      - ORTHANC_PASSWORD=quantum123
    depends_on:
      - app-db
      - pacs
    restart: always
    networks:
      - pacs

networks:
  pacs:
    external: true
