version: '3.8'
services:
  dicom-router:
    image: registry.dto.kemkes.go.id/pub/dicom-router:latest
    container_name: dicom-router
    platform: linux/amd64
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "11112:11112"
      - "18080:8080" # Mapping to avoided conflict if 8080 is used
    environment:
      - AE_TITLE=QTM-ROUTER  
      - ORG_ID=${ORG_ID}
      - CLIENT=${CLIENT_ID}
      - SECRET=${CLIENT_SECRET}
      - WEBHOOK_URL=http://quantum-web:3001/api/dicom/webhook
      - WEBHOOK_USER=admin
      - WEBHOOK_PASSWORD=${INTERNAL_PACS_KEY}
      - URL=${SATUSEHAT_URL}
    networks:
      - pacs
    entrypoint: /bin/bash -c "sed -i 's/\$$ORG_ID_A/\$$ORG_ID/g; s/\$$CLIENT_A/\$$CLIENT/g; s/\$$SECRET_A/\$$SECRET/g' /app/router.conf && exec /app/entrypoint.sh"

networks:
  pacs:
    external: true
