version: '3.8'
services:
  dicom-router:
    image: registry.dto.kemkes.go.id/pub/dicom-router:latest
    container_name: dicom-router
    platform: linux/amd64
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "11112:11112"
      - "18080:8080"
    environment:
      - AE_TITLE=QTM
      - ORG_ID=${ORG_ID}
      - CLIENT=${CLIENT_ID}
      - SECRET=${CLIENT_SECRET}
      - WEBHOOK_URL=http://quantum-web:3001/api/dicom/webhook
      - WEBHOOK_USER=admin
      - WEBHOOK_PASSWORD=${INTERNAL_PACS_KEY}
      - URL=${SATUSEHAT_URL}
    networks:
      - pacs
    entrypoint:
      - /bin/bash
      - -c
      - |
        cat <<EOF > /app/router.conf
        [satusehat]
        url = $$URL
        dicom_pathsuffix = /dicom/v1/dicomWeb/studies
        fhir_pathsuffix = /fhir-r4/v1
        tz_name = Asia/Jakarta
        ae_title = DCMROUTER
        dicom_port = 11112
        dcm_dir = /in/
        http_port = 8080
        webhook_url = $$WEBHOOK_URL
        webhook_user = $$WEBHOOK_USER
        webhook_password = $$WEBHOOK_PASSWORD

        [satusehat.default]
        calling_ae_title = $$AE_TITLE
        organization_id = $$ORG_ID
        client_key = $$CLIENT
        secret_key = $$SECRET
        EOF
        exec /app/entrypoint.sh

networks:
  pacs:
    external: true
